### ISSUE TITLE
Mise en place des permissions

### ISSUE THREAD

**Issue by Alexandre-re-RE** [Alexandre-re-RE/metastock-rest-api#52]

**Comment by riveur** [comment]
Permissions :

INFO: **Logistician** hérite des permissions de **Warehouseman**

### Account

- Voir un compte : **Logistician**
- Voir tous les comptes : **Logistician**
- Créer un compte : Personne
- Modifier son compte : **Warehouseman** (un utilisateur peut modifier uniquement son compte)
- Supprimer un compte : Personne
- Archiver un compte : **Logistician** (un utilisateur ne peut pas archiver son propre compte)

### Movement

- Voir un mouvement : **Logistician**
- Voir tous les mouvements : **Logistician**
- Créer un mouvement : **Warehouseman**
- Modifier un mouvement: Personne
- Supprimer un mouvement: Personne

### Product

- Voir un produit: **Warehouseman**
- Voir tous les produits : **Warehouseman**
- Créer un produit : **Logistician**
- Modifier un produit : **Logistician**
- Supprimer un produit : Personne
- Archiver un produit : **Logistician**

**Comment by riveur** [comment]
Pull request: [https://github.com/Alexandre-re-RE/metastock-rest-api/pull/60](https://github.com/Alexandre-re-RE/metastock-rest-api/pull/60)
